const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const {atomicJson,fileLock}=require('./storage.cjs');const {classify,timestamp}=require('./event-classifier.cjs');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function title(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function publisher(row){try{return new URL(row.url).hostname.toLowerCase().replace(/^www\./,'');}catch{return null;}}
function published(row){const t=timestamp(row.source_published_at||row.publishedAt);if(!t.value||(t.precision!=='date'&&t.timezone!=='UTC'))return null;const n=Date.parse(t.value);return Number.isFinite(n)?n:null;}
const STOP=new Set('a an the of for to in on and with from by at contract contracts award awarded awards wins won receives received million billion thousand usd rtx company companies announces announcement'.split(' '));
function tokens(value){return new Set(title(value).split(' ').filter(t=>t.length>2&&!STOP.has(t)&&!/^\d+$/.test(t)));}
function amount(event){const a=event.financial.headlineAmount;return a?{value:a.value,currency:a.currency}:null;}
function candidates(rows){
 const prepared=rows.map(row=>({row,normalized:title(row.title),time:published(row),host:publisher(row),event:classify(row),words:tokens(row.title),numbers:(title(row.title).match(/\b\d+\b/g)||[]).sort()})).filter(r=>r.normalized.length>=40&&r.time!==null&&r.host).sort((a,b)=>b.time-a.time);
 const buckets=new Map();for(const item of prepared){const keys=['title:'+item.normalized];if(item.event.eventType!=='OTHER_OR_UNCLEAR'){for(const company of item.row.companyMentions||[])keys.push('company:'+company);if(item.event.contractId)keys.push('contract:'+item.event.contractId);}for(const key of keys){const list=buckets.get(key)||[];list.push(item);buckets.set(key,list);}}
 const seen=new Set(),results=[];
 for(const list of buckets.values())for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){
  const a=list[i],b=list[j],pair=[a.row,b.row].sort((a,b)=>a.id.localeCompare(b.id)),pairKey=pair.map(r=>r.id).join('|');if(seen.has(pairKey))continue;seen.add(pairKey);
  if(a.row.sourceId&&a.row.sourceId===b.row.sourceId||a.host===b.host||Math.abs(a.time-b.time)>7*86400000||a.event.eventType!==b.event.eventType||JSON.stringify(amount(a.event))!==JSON.stringify(amount(b.event))||a.event.contractId&&b.event.contractId&&a.event.contractId!==b.event.contractId)continue;
  const exact=a.normalized===b.normalized;let shared=[],similarity=1;
  if(!exact){if(a.event.eventType==='OTHER_OR_UNCLEAR'||JSON.stringify(a.numbers)!==JSON.stringify(b.numbers))continue;const anchor=(a.row.companyMentions||[]).some(c=>(b.row.companyMentions||[]).includes(c))||a.event.contractId&&a.event.contractId===b.event.contractId;if(!anchor)continue;shared=[...a.words].filter(t=>b.words.has(t));similarity=shared.length/new Set([...a.words,...b.words]).size;if(shared.length<(amount(a.event)?3:4)||similarity<0.65)continue;}
  results.push({id:hash([2,...pair.map(r=>[r.id,r.titleHash||hash(r.title),r.source_published_at||r.publishedAt,r.url])]),matcherVersion:2,matchKind:exact?'exact_headline':'anchored_rewording',similarity:exact?null:Math.round(similarity*100),sharedTerms:shared,evidence:pair.map(r=>({id:r.id,title:r.title,url:r.url,sourceName:r.sourceName,publishedAt:r.source_published_at||r.publishedAt,contentHash:r.titleHash||null})),reason:exact?'Exact normalized headline across different source hosts; compatible provisional type/amount and publication dates within seven days.':'Shared research-company or reported-contract anchor, compatible provisional event type/amount, identical numeric tokens, overlapping subject terms and publication dates within seven days.',status:'needs_review',limitations:'Not proof of one award, independent corroboration, recipient identity or financial materiality. Company-name anchors are research cues; dates may have date-only precision.'});if(results.length>=500)return results;
 }return results;
}
function createAnnouncementReview(dir,getRows){const file=path.join(dir,'announcement-reviews.json');function load(){return fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):{version:1,decisions:{}};}
function query(){const stored=load(),current=candidates(getRows()),ids=new Set(current.map(c=>c.id));return {candidates:current.map(c=>({...c,decision:stored.decisions[c.id]||null})),staleDecisions:Object.values(stored.decisions).filter(d=>!ids.has(d.candidateId)),coverage:'Exact headlines and conservative anchored rewordings; no automatic merging or alert suppression. Unknown publication dates, conflicting amounts/types/numbers and unanchored paraphrases are excluded.'};}
function decide(input){if(!input||!['related','distinct'].includes(input.decision)||typeof input.note!=='string'||input.note.trim().length<5||input.note.length>2000)throw new Error('Choose related/distinct and provide a review reason (5–2000 characters)');const candidate=candidates(getRows()).find(c=>c.id===input.id);if(!candidate)throw new Error('Candidate changed or unavailable; reload before reviewing');const release=fileLock(file);try{const state=load(),prior=state.decisions[input.id],decision={candidateId:input.id,matcherVersion:candidate.matcherVersion,matchKind:candidate.matchKind,similarity:candidate.similarity,sharedTerms:candidate.sharedTerms,decision:input.decision,note:input.note.trim(),reviewedAt:new Date().toISOString(),evidence:candidate.evidence,history:[...(prior?.history||[]),...(prior?[{decision:prior.decision,note:prior.note,reviewedAt:prior.reviewedAt}]:[])]};state.decisions[input.id]=decision;atomicJson(file,state);return decision;}finally{release();}}
return {query,decide};}
module.exports={candidates,createAnnouncementReview};
