const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const {atomicJson,fileLock}=require('./storage.cjs');const {classify,timestamp}=require('./event-classifier.cjs');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function title(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function publisher(row){try{return new URL(row.url).hostname.toLowerCase().replace(/^www\./,'');}catch{return null;}}
function published(row){const t=timestamp(row.source_published_at||row.publishedAt);if(!t.value||(t.precision!=='date'&&t.timezone!=='UTC'))return null;const n=Date.parse(t.value);return Number.isFinite(n)?n:null;}
function candidates(rows){const buckets=new Map();for(const row of rows){const key=title(row.title);if(key.length<40||published(row)===null||!publisher(row))continue;const list=buckets.get(key)||[];list.push(row);buckets.set(key,list);}const results=[];for(const list of buckets.values())for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(a.sourceId&&a.sourceId===b.sourceId||publisher(a)===publisher(b)||Math.abs(published(a)-published(b))>7*86400000)continue;const ea=classify(a),eb=classify(b);if(ea.eventType!==eb.eventType||JSON.stringify(ea.financial.headlineAmount)!==JSON.stringify(eb.financial.headlineAmount)||ea.contractId&&eb.contractId&&ea.contractId!==eb.contractId)continue;const pair=[a,b].sort((a,b)=>a.id.localeCompare(b.id));results.push({id:hash(pair.map(r=>[r.id,r.titleHash||hash(r.title)])),evidence:pair.map(r=>({id:r.id,title:r.title,url:r.url,sourceName:r.sourceName,publishedAt:r.source_published_at||r.publishedAt,contentHash:r.titleHash||null})),reason:'Exact normalized headline across different source hosts; compatible provisional type/amount, no conflicting known contract ID; source publications within seven days.',status:'needs_review',limitations:'Not proof of one award, independent corroboration, recipient identity or financial materiality. Dates may have date-only precision.'});if(results.length>=500)return results;}return results;}
function createAnnouncementReview(dir,getRows){const file=path.join(dir,'announcement-reviews.json');function load(){return fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):{version:1,decisions:{}};}
function query(){const stored=load(),current=candidates(getRows()),ids=new Set(current.map(c=>c.id));return {candidates:current.map(c=>({...c,decision:stored.decisions[c.id]||null})),staleDecisions:Object.values(stored.decisions).filter(d=>!ids.has(d.candidateId)),coverage:'Strict exact-headline candidates only; no automatic merging or alert suppression. Unknown publication dates and changed wording are excluded.'};}
function decide(input){if(!input||!['related','distinct'].includes(input.decision)||typeof input.note!=='string'||input.note.trim().length<5||input.note.length>2000)throw new Error('Choose related/distinct and provide a review reason (5–2000 characters)');const candidate=candidates(getRows()).find(c=>c.id===input.id);if(!candidate)throw new Error('Candidate changed or unavailable; reload before reviewing');const release=fileLock(file);try{const state=load(),prior=state.decisions[input.id],decision={candidateId:input.id,decision:input.decision,note:input.note.trim(),reviewedAt:new Date().toISOString(),evidence:candidate.evidence,history:[...(prior?.history||[]),...(prior?[{decision:prior.decision,note:prior.note,reviewedAt:prior.reviewedAt}]:[])]};state.decisions[input.id]=decision;atomicJson(file,state);return decision;}finally{release();}}
return {query,decide};}
module.exports={candidates,createAnnouncementReview};
