const {classifyDocument,CLASSIFIER_VERSION}=require('./event-classifier.cjs');
const {atomicJson,fileLock}=require('./storage.cjs');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),dns=require('node:dns').promises,https=require('node:https'),net=require('node:net');
const HOSTS=new Set(['www.rtx.com','news.lockheedmartin.com','www.nasa.gov','www.hhs.gov','www.gsa.gov','breakingdefense.com']);
function publicAddress(ip){if(net.isIP(ip)!==4)return false;const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19));}
function destination(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||!HOSTS.has(u.hostname)||u.searchParams.has('api_key'))throw new Error('Document destination is not approved');return u;}
async function download(value){const u=destination(value);const addresses=await dns.lookup(u.hostname,{all:true,family:4});if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw new Error('Document destination resolves to a restricted address');return new Promise((resolve,reject)=>{const req=https.get(u,{lookup:(_host,options,cb)=>options.all?cb(null,[addresses[0]]):cb(null,addresses[0].address,4),headers:{'User-Agent':'ContractSentinel/0.14 public-document-research',Accept:'text/html'},signal:AbortSignal.timeout(20000)},res=>{if(res.statusCode!==200){res.resume();reject(new Error('Document HTTP '+res.statusCode+'; redirects are not followed'));return;}if(!/^text\/html\b/i.test(res.headers['content-type']||'')){res.resume();reject(new Error('Only HTML documents are supported in this milestone'));return;}let size=0,chunks=[];res.on('data',chunk=>{size+=chunk.length;if(size>5000000){res.destroy(new Error('Document exceeds 5MB limit'));return;}chunks.push(chunk)});res.on('error',reject);res.on('end',()=>resolve(Buffer.concat(chunks)));});req.on('error',()=>reject(new Error('Document retrieval failed; prior snapshots preserved')));});}
function plain(value){return value.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();}
function passages(html){html=html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||html;const footer=html.search(/<[^>]+class=["'][^"']*esds-article-footer/i);if(footer>=0)html=html.slice(0,footer);const cleaned=html.replace(/<(script|style|nav|footer|header)\b[^>]*>[\s\S]*?<\/\1>/gi,'');return [...cleaned.matchAll(/<(p|h[1-6]|li|td|th)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(m=>plain(m[2])).filter(t=>t.length>=30).map((text,i)=>({id:'p'+(i+1),text,hash:crypto.createHash('sha256').update(text).digest('hex'),researchCue:/\$|contract|award|supplier|production|obligat|option|million|billion/i.test(text)}));}
function createDocumentStore(dataDir){const directory=path.join(dataDir,'documents');fs.mkdirSync(directory,{recursive:true});const indexFile=path.join(directory,'index.json');let busy=false;function load(){return fs.existsSync(indexFile)?JSON.parse(fs.readFileSync(indexFile)):{};}function get(id){if(!/^[a-f0-9]{64}$/.test(id))throw new Error('Invalid evidence ID');return load()[id]||null;}
function ingestUnlocked(evidence,raw){if(!/^[a-f0-9]{64}$/.test(evidence.id))throw new Error('Invalid evidence ID');destination(evidence.url);const index=load(),prior=index[evidence.id],hash=crypto.createHash('sha256').update(raw).digest('hex'),items=passages(raw.toString('utf8'));if(!items.length)throw new Error('No supported HTML passages found; prior snapshot preserved');const textHash=crypto.createHash('sha256').update(items.map(p=>p.text).join('\n')).digest('hex'),old=prior?.versions.at(-1);if(old?.hash===hash&&old.extractionVersion===2&&old.classificationVersion===CLASSIFIER_VERSION)return {...prior,unchanged:true};const oldHashes=new Set((old?.passages||[]).map(p=>p.hash)),newHashes=new Set(items.map(p=>p.hash));const version={hash,textHash,retrievedAt:new Date().toISOString(),sourceUrl:evidence.url,sourceName:evidence.sourceName,sourceClass:evidence.sourceClass,publishedAt:evidence.publishedAt||null,format:'HTML',extractionVersion:2,classificationVersion:CLASSIFIER_VERSION,candidateEvents:classifyDocument(evidence,items),reviewStatus:'extracted_not_analyst_verified',passages:items,change:old?{kind:old.extractionVersion!==2||old.classificationVersion!==CLASSIFIER_VERSION?'extraction_updated':old.textHash===textHash?'formatting_only':'text_changed',previousHash:old.hash,added:items.filter(p=>!oldHashes.has(p.hash)).map(p=>p.id),removed:(old.passages||[]).filter(p=>!newHashes.has(p.hash)).map(p=>({id:p.id,text:p.text}))}:{kind:'first_snapshot',added:[],removed:[]}};const original=path.join(directory,hash+'.html');if(!fs.existsSync(original)){const temporary=original+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(temporary,raw,{flag:'wx'});fs.renameSync(temporary,original);}index[evidence.id]={evidenceId:evidence.id,title:evidence.title,versions:[...(prior?.versions||[]),version]};atomicJson(indexFile,index);return index[evidence.id];}
function ingest(evidence,raw){const release=fileLock(indexFile);try{return ingestUnlocked(evidence,raw);}finally{release();}}
async function fetchDocument(evidence){if(busy)throw new Error('Document retrieval already running');busy=true;try{return ingest(evidence,await download(evidence.url));}finally{busy=false;}}
return {get,fetchDocument,ingest};}
module.exports={createDocumentStore,passages,publicAddress,destination};


