const crypto=require('node:crypto');
const cues={contract:/\b(contract|awarded|task order|delivery order|procurement)\b/i,supplier:/\b(subcontract|supplier|teaming|production partner)\b/i,growth:/\b(expansion|expand(?:s|ed|ing)?|new facility|capacity|production ramp|backlog|funding)\b/i,ipo:/\b(IPO|initial public offering|S-1|F-1|registration statement|public listing)\b/i,negative:/\b(termination|cancell?ation|deobligation|withdrawn|bankrupt)\b/i};
function plain(value){return String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ').replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(_,s)=>{const n=s[0].toLowerCase()==='x'?parseInt(s.slice(1),16):Number(s);return n>=0&&n<=0x10ffff?String.fromCodePoint(n):''}).replace(/&(?:amp|lt|gt|quot|apos|nbsp);/g,s=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&nbsp;':' '}[s])).replace(/\s+/g,' ').trim()}
function xmlTag(item,tag){return item.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'))?.[1]||''}
function safeUrl(value,base){try{const u=new URL(value,base);return u.protocol==='https:'?u.href.split('#')[0]:null}catch{return null}}
function parseFeed(xml,source){if(!/<(?:rss|feed)\b/i.test(xml))throw new Error('Expected RSS or Atom feed');return [...xml.matchAll(/<(item|entry)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(([,type,item])=>{const link=type.toLowerCase()==='entry'?item.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*\/?\s*>/i)?.[1]:xmlTag(item,'link');return {title:plain(xmlTag(item,'title')),url:safeUrl(plain(link),source.url),publishedAt:plain(xmlTag(item,'pubDate')||xmlTag(item,'published')||xmlTag(item,'updated'))||null}}).filter(r=>r.title&&r.url).slice(0,100)}
function parseIndex(html,source){const pattern=new RegExp(source.articlePattern,'i'),seen=new Set();return [...html.matchAll(/<a\b([^>]*?)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi)].map(([,before,href,after,text])=>({url:safeUrl(plain(href),source.url),title:plain(text)||plain((before+after).match(/(?:aria-label|title)=["']([^"']+)["']/i)?.[1]),publishedAt:null})).filter(r=>r.url&&pattern.test(r.url)&&r.title.length>15&&!seen.has(r.url)&&seen.add(r.url)).slice(0,60)}
function annotate(title,watchlist){return {cues:Object.entries(cues).filter(([,pattern])=>pattern.test(title)).map(([name])=>name),companyMentions:watchlist.filter(c=>[c.name,...c.aliases].some(name=>{const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`\\b${escaped}\\b`,'i').test(title)})).map(c=>c.name)}}

module.exports={parseFeed,parseIndex,annotate,plain,safeUrl};
