const assert=require('node:assert/strict'),{classify,timestamp}=require('../event-classifier.cjs');
const row=title=>({title,sourceClass:'official_announcement',url:'https://example.gov/a',firstSeen:'2026-09-30T12:00:00Z'});
for(const [text,type] of [['Contract terminated','CANCELLATION_OR_TERMINATION'],['Option not exercised','CANCELLATION_OR_TERMINATION'],['Bid protest sustained','PROTEST_OR_CORRECTIVE_ACTION'],['Draft RFP for radar procurement','DRAFT_SOLICITATION'],['Sources sought for satellites','SOURCES_SOUGHT_RFI'],['Selected for negotiations on contract','DOWN_SELECTION'],['IDIQ contract awarded','CONTRACT_VEHICLE_AWARD'],['Funded task order awarded','FUNDED_TASK_OR_DELIVERY_ORDER'],['Option exercised on contract','OPTION_EXERCISE'],['Contract modification announced','CONTRACT_MODIFICATION'],['Budget request for satellites','PROPOSED_FUNDING'],['Enacted funding for submarine program','ENACTED_FUNDING'],['Awarded a grant','GRANT'],['Federal loan agreement','LOAN_OR_GUARANTEE'],['Manufacturing expansion announced','INDUSTRIAL_EXPANSION'],['Company awarded a contract','DEFINITIVE_CONTRACT_AWARD']])assert.equal(classify(row(text)).eventType,type,text);
for(const text of ['Company not awarded a contract','Company denies contract terminated','Company could be awarded a contract','AI and RFI conference'])assert.equal(classify(row(text)).eventType,'OTHER_OR_UNCLEAR',text);
const historical=classify(row('Previously awarded a contract'));assert.equal(historical.priority,'LOW');assert.ok(historical.flags.includes('historical_or_repeated_language'));
const notice=classify({...row('General procurement'),noticeId:'a',noticeType:'Award Notice',award:{recipientName:'Acme',amount:100,recipientUei:'ABC'}});assert.equal(notice.eventType,'OTHER_OR_UNCLEAR');assert.equal(notice.financial.headlineAmount.value,100);assert.equal(notice.financial.newlyObligatedAmount,null);assert.equal(notice.financial.companyAllocation,null);assert.equal(notice.identity.publicParent,null);assert.equal(notice.dimensions.financialMateriality,'UNKNOWN');assert.notEqual(notice.priority,'HIGH');
assert.equal(timestamp('2026-09-30').precision,'date');assert.equal(timestamp('2026-09-30').timezone,null);assert.equal(timestamp('2026-09-30 09:00:00').timezone,'unspecified');assert.equal(timestamp('2026-09-30T09:00:00-04:00').value,'2026-09-30T13:00:00.000Z');assert.equal(timestamp('September 30, 2026').precision,'unparsed');
console.log('PASS event types, negation, speculation, historical flags, ambiguous notices, financial separation, unknown identities and timestamp precision');

assert.equal(classify({...row('Draft RFP for radar'),noticeId:'a',noticeType:'Solicitation'}).eventType,'OTHER_OR_UNCLEAR');
assert.equal(classify(row('Budget request for satellites')).priority,'LOW');

assert.equal(classify({...row('Company awarded a contract'),publishedAt:'2026-08-01T12:00:00Z'}).priority,'LOW');
assert.equal(timestamp('2026-02-30').precision,'invalid_date');
for(const [text,type] of [['Prototype agreement awarded','PROTOTYPE_AWARD'],['Procurement forecast published','PROCUREMENT_FORECAST'],['Request for proposals for satellite program','FINAL_SOLICITATION'],['Full-rate production transition','PRODUCTION_TRANSITION']])assert.equal(classify(row(text)).eventType,type);

assert.equal(timestamp('Tue, 13 Jan 2026 12:00:17 EDT').value,'2026-01-13T16:00:17.000Z');assert.equal(classify({...row('GSA awards leasing support contract'),publishedAt:'Tue, 13 Jan 2026 12:00:17 EDT'}).priority,'LOW');
