const assert=require('node:assert/strict'),{classify}=require('../event-classifier.cjs');const row=title=>({title,sourceClass:'company_statement',publishedAt:'2026-08-01',firstSeen:'2026-09-30T16:00:00Z'});
for(const text of ['Company awarded a $200 million contract','Company wins a USD 200 million production contract','Company receives a two hundred million dollar contract','Company was awarded a £200 million contract for radar systems']){const event=classify(row(text));assert.equal(event.eventType,'DEFINITIVE_CONTRACT_AWARD',text);assert.equal(event.classificationStatus,'provisional_requires_review');assert.equal(event.financial.newlyObligatedAmount,null);assert.equal(event.priority,'LOW');assert.ok(event.flags.includes('publication_predates_detection_by_over_seven_days'));}
for(const text of ['Company may be awarded a $200 million contract','Company was not awarded a $200 million contract','Company selected for negotiations on a $200 million contract'])assert.notEqual(classify(row(text)).eventType,'DEFINITIVE_CONTRACT_AWARD',text);
const multiple=classify(row('Company awarded a $200 million contract; option exercised on another contract'));assert.ok(multiple.candidateEventTypes.includes('OPTION_EXERCISE'));assert.ok(multiple.candidateEventTypes.includes('DEFINITIVE_CONTRACT_AWARD'));assert.ok(multiple.flags.includes('multiple_event_phrases_require_review'));console.log('PASS realistic award amounts, uncertainty, date-only staleness and multiple candidate events');

assert.equal(classify(row('Company awarded a $200 million contract')).financial.headlineAmount.value,200000000);assert.equal(classify(row('Company awarded a £200 million contract')).financial.headlineAmount.currency,'GBP');assert.equal(classify(row('Company awarded a $30 million modification to its existing radar contract')).eventType,'CONTRACT_MODIFICATION');

const {classifyDocument}=require('../event-classifier.cjs');const candidates=classifyDocument(row('Document'),[{id:'p1',text:'Company awarded a $200 million contract.'},{id:'p2',text:'The Navy exercised an option on a separate sustainment agreement.'},{id:'p3',text:'Another company could win a contract next year.'}]);assert.equal(candidates.length,3);assert.equal(candidates[0].interpretation.eventType,'DEFINITIVE_CONTRACT_AWARD');assert.equal(candidates[1].interpretation.eventType,'OPTION_EXERCISE');assert.equal(candidates[2].interpretation.eventType,'OTHER_OR_UNCLEAR');

assert.equal(classify({...row('Indefinite delivery indefinite quantity architect contract'),noticeId:'a',noticeType:'Presolicitation'}).eventType,'OTHER_OR_UNCLEAR');assert.equal(classify(row('IDIQ contract for upcoming procurement')).eventType,'OTHER_OR_UNCLEAR');

assert.equal(classify(row('Company received a $300 million contract for support services')).eventType,'DEFINITIVE_CONTRACT_AWARD');assert.equal(classify(row('Company won a $300 million contract for radar')).financial.headlineAmount.value,300000000);
